version: '3.2'

services:
  web:
    image: webdevops/php-nginx:7.2
    environment:
      WEB_DOCUMENT_ROOT: /application/code/public
    links:
      - database
    ports:
      - 80
    volumes:
      - .:/application/code:rw
  pgadmin:
    image: thajeztah/pgadmin4
    ports:
      - "5050:5050"
    links:
      - database
  database:
    image: postgres:10.1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret_password
    ports:
      - "5432:5432"
    volumes:
      - ./database:/var/lib/mysql:rw
