version: '3.2'

services:
  database:
    image: postgres:10.1
    environment:
      POSTGRES_DB: db_name
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret_password
      PGDATA: /var/lib/postgres/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - ./docker/database:/var/lib/postgresql/data
  php:
    build: ./docker/php
    links:
      - database
    volumes:
      - .:/host
  web:
    image: nginx:1.13.8
    links:
      - php
    ports:
      - 80
    volumes:
      - .:/host
      - ./docker/nginx.conf:/etc/nginx/nginx.conf
  pgadmin:
    image: thajeztah/pgadmin4
    ports:
      - "5050:5050"
    links:
      - database
